### ISSUE TITLE
How to configure?

### ISSUE THREAD

**Issue by linjunpop** [dmarkow/jquery-mobile-rails#1]
Where can I put the configuration code?

I create a new file `jquery_mobile_config.js.coffee`

```
    $(document).bind("mobileinit", () ->
      $.mobile.ajaxEnabled = false
      $.mobile.ajaxLinksEnabled = false
      $.mobile.ajaxFormsEnabled = false
      #$.mobile.defaultTransition = 'none'
    )
```

In my `application.js`

```
    //= require jquery_mobile_config
    //= require jquery.mobile
```

The configuration is not working.

**Comment by tscolari** [comment]
Hi there,
I created a test application here and it seems to work.
The only difference is that I included jquery and jquery_ujs before the mobile_config

``` javascript
//= require jquery
//= require jquery_ujs
//= require jquery_mobile_config
//= require jquery.mobile
```

If you want to take a look, I pushed it here: https://github.com/tscolari/jquery-mobile-config-tests

**Comment by linjunpop** [comment]
Fine, I think the issue is caused by requiring `jquery-ui` before `jquery.mobile`

```
    //= require jquery
    //= require jquery-ui
    //= require jquery_ujs
    //= require jquery_mobile_config
    //= require query.mobile
```

And this works fine:

```
    //= require jquery
    //= require jquery_ujs
    //= require jquery_mobile_config
    //= require query.mobile
    //= require jquery-ui
```

Thanks

**Comment by tscolari** [comment]
You are welcome
It's good to hear it is working!
