### ISSUE TITLE
In production, path to images is wrong

### ISSUE THREAD

**Issue by gregorym** [dmarkow/jquery-mobile-rails#16]
Hi,

The jqm icons/images does not appear in production.

In production:

```
.ui-icon, .ui-icon-searchfield:after {
  background: #666;
  background: rgba(0, 0, 0, 0.4);
  background-image: image-url("jquery-mobile/icons-18-white.png");
  background-repeat: no-repeat;
  -moz-border-radius: 9px;
  -webkit-border-radius: 9px;
  border-radius: 9px; }
```

In dev:

```
.ui-icon, .ui-icon-searchfield:after {
  background: #666;
  background: rgba(0, 0, 0, 0.4);
  background-image: url(/assets/jquery-mobile/icons-18-white.png);
  background-repeat: no-repeat;
  -moz-border-radius: 9px;
  -webkit-border-radius: 9px;
  border-radius: 9px;
}
```

The `/assets/`is missing in production.

**Comment by chewi** [comment]
You're not comparing like with like here. The first snippet is SCSS, the second is regular CSS. The first should get transformed into the second before being sent down the wire. If it's not then something is wrong with your setup.

**Comment by mrgcohen** [comment]
yes, i'm having the same problem. Images don't seem to be including themself properly. 

When you are trying to precompile assets it looks like images are not being included.  Is there something I have to set for jquery-mobile-rails?

**Actually this may be a relative root issue**

where it should be
http://site/assets/jquery-mobile/ajax-loader-cad1a448fe000d9643c57860e5493861.gif

where it is
http://site/rails_ap_name/assets/jquery-mobile/ajax-loader-cad1a448fe000d9643c57860e5493861.gif

**Comment by renius** [comment]
Is there are any solutions?
Forced to use the jquery.mobile directly without gem

**Comment by mrgcohen** [comment]
No this was a relative root issue. Solved when I updated glass fish variable when running as jruby app.

**Comment by znz** [comment]
I met same problem.
And I found resolution of it.

When assets files in vendor/assets are not processed when `rake assets:precompile`,
and files in app/assets are processed when `rake assets:precompile`.

Workaround with current released gems is adding `config.assets.precompile += %w( *.gif *.png )` in `config/environments/production.rb`.

**Comment by dmarkow** [comment]
Closing this issue as it hasn't been updated in a while. If you're still running into issue with this, please reopen and let me know.

**Comment by billrichards** [comment]
I encountered the same issue. znz's solution and running rake assets:precompile again worked for me

**Comment by dmarkow** [comment]
@billrichards I think this might be the same thing as issue #36 opened yesterday. I need to do some testing to make sure JQM works fine with precompiled assets in production and push out a new version. You can track #36 for progress on this.

**Comment by billrichards** [comment]
@dmarkow confirming that 1.4.4.1 resolved the issue I noted above.  thanks!
