### ISSUE TITLE
jquery mobile 1.2.0 not compaitble with jquery 1.9.0

### ISSUE THREAD

**Issue by thoughtafter** [dmarkow/jquery-mobile-rails#19]
This means the jquery_mobile_rails 1.2.0 gem is not compatible with jquery-rails >= 2.2.0. Jquery mobile calls $.browser which has been removed in jquery 1.9.0. The gemspec should reflect this.

**Comment by Genkilabs** [comment]
JQM 1.3.0 rc1 will work with jQuery 1.9.
See if this works for you, https://github.com/Genkilabs/jquery-mobile-rails or bump it to whatever comes next.

**Comment by dmarkow** [comment]
As mentioned, the newer versions of jQuery Mobile are compatible.
