### ISSUE TITLE
cannot call methods on loader prior to initialization

### ISSUE THREAD

**Issue by jwarzech** [dmarkow/jquery-mobile-rails#20]
I am currently running a rails (3.2) app with jquery-rails (2.1.4) and jquery_mobile_rails (1.3.b1).

If I include 'jquery.mobile' in my application.js I receive the following error on load:

Uncaught Error: cannot call methods on loader prior to initialization; attempted to call method 'show' - jquery.js

**Comment by tscolari** [comment]
I'm not sure what could cause this, could you paste your application.js manifest here?

**Comment by g8d3** [comment]
I am having the same problem, but I am not even using Rails.

`Uncaught Error: cannot call methods on loader prior to initialization; attempted to call method 'hide' - jquery.js`

**Comment by tscolari** [comment]
My guess would be that jquery mobile is being loaded before jquery itself, or some other dependency.
Is this possible? 
Could you paste your JavaScript includes order?

**Comment by g8d3** [comment]
I checked, I have jquery and then jquery mobile.

``` coffeescript
$ ->
  a = -> $('body').html( Template.mobile() )
  setTimeout a, 100 # works
  setTimeout a, 50 # fails
```

Anyway to solve this error with timeout did not solve my other problem, I have this:

``` html
<body class="ui-mobile-viewport ui-overlay-c">
  <div data-role="page" id="page1">
    <div data-theme="a" data-role="header">
      <h3>Header</h3>
    </div>

    <div data-role="content">
      <a data-role="button" href="#page1">Button</a>
    </div>

    <div data-theme="a" data-role="footer" data-position="fixed">
      <h3>Footer</h3>
    </div>
  </div>
</body>
```

But nothing appears, neither error in browser console.

**Comment by pramodhkumar-it** [comment]
i cleared the same issue by adding  data-ajax="false" in anchor tag,dont know the reason but it let job done for me.

**Comment by dmarkow** [comment]
Closing this as it's been inactive for some time, and Rails / jquery-rails / jquery-mobile-rails have all seen some updates in the meantime. If this is still happening, please reopen the issue (and ideally provide your Gemfile and application.js files)
