### ISSUE TITLE
Can you upgrade to include a branch with 2.beta?

### ISSUE THREAD

**Issue by ashrocket** [dmarkow/jquery-mobile-rails#29]
<script src="http://code.jquery.com/mobile/1.0b2/jquery.mobile-1.0b2.min.js"></script>

Compeltely debundles the css and widgets from the core which is great for using bootstrap with jquery mobile, prevents css conflicts

**Comment by dmarkow** [comment]
I'm not sure which exact version you're referring to? 1.4.0 is on rc1 right now (which there is a branch for), and our master branch points to the latest release (1.3.2). Can you give a link to the beta version you're referring to so I can look into it? Thanks!

**Comment by ashrocket** [comment]
Doh!   I totally had an old version of your gem.

I was looking for 1.3.2 jquery mobile 
thatnks
