### ISSUE TITLE
Routing error

### ISSUE THREAD

**Issue by nextofsearch** [dmarkow/jquery-mobile-rails#3]
Hi,
I installed the gem and followed your instructions but get the following errors:

ActionController::RoutingError (No route matches [GET] "/assets/jquery.mobile.min-04b0fe32127b53b251f5bdc9562fde6c.css"):

It only happens when I put it on Heroku and it is fine on my local browser with mobile user-agent.

I set "config.assets.compile = true" in production.rb but didn't help and I don't see any errors or warnings when git push to Heroku.

BTW, I find it very odd since your sample rails app don't have any insertions of jQuery.mobile in these two manifests and works fine. Do we really need these to be inserted or not?
https://github.com/tscolari/rails-mobile-app-sample/blob/master/app/assets/javascripts/application.js
https://github.com/tscolari/rails-mobile-app-sample/blob/master/app/assets/stylesheets/application.css

**Comment by tscolari** [comment]
Hello, 

I'll fix that on the sample app, indeed you must add jquery.mobile css/js to a manifest (or make it a manifest) for using it production.

Rails/Sprockets will only compile the assets that are manifests or that are included in a manifest.
