### ISSUE TITLE
Minified stylesheet image paths are incorrect

### ISSUE THREAD

**Issue by sman591** [dmarkow/jquery-mobile-rails#31]
`jquery.mobile.css.scss` and `jquery.mobile.min.css.scss` do not match up.

The image paths used in the original file all use `jquery-mobile/`, while a majority of the paths in the minified file use `images/`.

After further consideration, it looks like an issue with the `jquery_mobile_rails_css_fix` rake task. It renames the minified file to .scss, but doesn't replace all of the `images/` instances.

I then tried adding line breaks after every `{` character in the minified file, and the task ran as expected. Issue with the regex, perhaps? I couldn't figure it out.

**Comment by dmarkow** [comment]
Thanks! The regex was too greedy -- changing `(.*\.)` to `(.*?\.)` stopped it from matching the entire line.
