### ISSUE TITLE
Can't run rake task "jquery_mobile_rails_css_fix"

### ISSUE THREAD

**Issue by dickkirkland** [dmarkow/jquery-mobile-rails#32]
Followed all instructions on .rmd. Can't seem to run the rake task mentioned to rename file paths, etc. Also, I don't see it in the available rake tasks when performing rake -T -A. Any help would be greatly appreciated. Thanks in advance for reviewing.

**Comment by dmarkow** [comment]
The gem is currently locked to Rake 10.1.0 -- you may have something like 10.3.1 installed.

Usually a `bundle exec rake ...` will work if a normal `rake ...` fails.

**Comment by dickkirkland** [comment]
Thanks for the workaround. I appreciate it. I will try again soon.
