### ISSUE TITLE
ajax loader

### ISSUE THREAD

**Issue by lws68825** [dmarkow/jquery-mobile-rails#33]
I tried this gem, it works greatly. But  I found that the ajax-loader.gif did not show. Can anyone help?

**Comment by dmarkow** [comment]
How are you using it? Keep in mind the images are under a `jquery-mobile` folder so you would have to use them like this:

```
<%= image_tag "jquery-mobile/ajax-loader.gif" %>
```

**Comment by lws68825** [comment]
Thank you, dmarkow. I sovled the problem according to your instruction.
