### ISSUE TITLE
rails 3.2

### ISSUE THREAD

**Issue by alec-c4** [dmarkow/jquery-mobile-rails#4]
Hi,
could you please update dependencies to use with rails 3.2 and update gem in repo? Thanks a lot :)

**Comment by adahl** [comment]
I also need this. Thanks.

**Comment by dgdosen** [comment]
I'd like to see this too

**Comment by linuxonrails** [comment]
I also need this. This issue is very important (to me).

**Comment by tscolari** [comment]
Just to be sure, it's now working for rails 3.2 for you right?
there was a pull request few months ago fixing this, I forgot to ping back you here, sorry.

**Comment by linuxonrails** [comment]
It's working now for Rails 3.2.2. Thx!
