### ISSUE TITLE
Update Version to 1.1.0

### ISSUE THREAD

**Issue by f0086** [dmarkow/jquery-mobile-rails#7]
Please update the JQuery Mobile version to 1.1.0

**Comment by fred** [comment]
hi, I forked the project and im planning to do the upgrade to Latest Unstable Build: 1.1.0 RC1 

are you interested on a pull request?

aslo, anyone interested to help? 

this is my fork url https://github.com/fred/jquery-mobile-rails

**Comment by linuxonrails** [comment]
I am interested on upgrade to Latest Unstable Build 1.1.0 RC1!

Thx fred!

**Comment by fred** [comment]
linuxonrails, it's here: https://github.com/fred/jquery-mobile-rails/tree/110-rc1 
(branch 110-rc1)

**Comment by linuxonrails** [comment]
Very thanks fred!!!

**Comment by tscolari** [comment]
Guys sorry for the delay. 
I updated the javascript version to 1.1.0 now that it's final.
